version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  # Web Server
  web_clients:
    build:
      context: ./clients/.docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=clients
        - PHP_UPSTREAM_PORT=9000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./clients/:/var/www
      - ./clients/storage/logs/nginx/:/var/log/nginx
      - ./clients/.docker/nginx/sites/:/etc/nginx/sites-available
      - ./clients/.docker/nginx/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    depends_on:
      - app_clients
    image: "web-image"
    networks:
      - frontend
      - backend
  # Server Application Programming Interface
  app_clients:
    build:
      context: ./clients/.docker/php-fpm
    volumes:
      - ./clients/:/var/www
    working_dir: /var/www
    expose:
      - "9000"
    networks:
      - backend
    image: "app-image"
    depends_on:
      - database_clients
  # Database
  database_clients:
    build:
      context: ./clients/.docker/postgres-postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=clients
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    image: "db-image"
    networks:
      - backend
  # Eureuka server
  discovery:
    build: ./discovery-server
    ports:
      - "8761:8761"
    image: "discovery-server"
  config:
    build: ./config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/main/resources/centralRepo
        target: /config
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"
  # Zuul server
  gateway:
    build: ./zuul-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"

