version: "3.7"
services:
  app:
    build:
      args:
        user: yassine
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: clients
    container_name: clients-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - clients
  db:
    image: mysql:5.7
    container_name: clients-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - clients
  nginx:
    image: nginx:1.17-alpine
    container_name: clients-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - clients
  # Eureuka server
  discovery:
    build:  ../EurekaServer
    ports:
      - "8761:8761"
    image: "eureuka-server"
    networks:
      - clients
  gateway:
    build: ../Zuul-Gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8763:8763"
    image: "gateway-server"
    networks:
      - clients

networks:
  clients:
    driver: bridge
